FROM tomcat:9.0.104-jre17-temurin-noble

ADD http://54.89.141.120:8081/repository/maven-snapshots/com/mt/maven-web-application/0.0.2-SNAPSHOT/maven-web-application-0.0.2-20250420.160035-1.war /usr/local/tomcat/webapps/maven-web-app.war
